[package]
name = "clippy_crashfinder"
version = "0.1.0"
authors = ["Matthias Krüger <matthias.krueger@famsik.de>"]
edition = "2018"

[dependencies]
dirs = "1.0"
#rayon = "1.0"
rustwide = "0.3.1"
env_logger = "0.7.0"
log = "0.4.8"